### ISSUE TITLE
Add line number to parsers callback function

### ISSUE THREAD

**Issue by tjbenton** [DSSWG/DSS#53]
I already did this to the file but I thought other people might like to see this feature added. In the `_dss.parse` function I added the following.

After the [`index = block.indexOf(line);`](https://github.com/darcyclarke/DSS/blob/master/dss.js#L203) variable, inside the [`parser`](https://github.com/darcyclarke/DSS/blob/master/dss.js#L194) function I added this.
```js
var endOfBlockRegex = /\n\s*#{{(\d*)}}/,
    endOfBlock = block.match(endOfBlockRegex)[1],
    block = block.replace(endOfBlockRegex, "");
```
Then added `endOfBlock` to line [205](https://github.com/darcyclarke/DSS/blob/master/dss.js#L205)
```js
line[name] = (variable) ? variable.apply(null, [index, description, block, file, endOfBlock]) : '';
```
Then on line [314](https://github.com/darcyclarke/DSS/blob/master/dss.js#L314) inside if statement that stores the current block if done. I added `.concat("\n #{{" + lineNum + "}}")` to the `current_block`
```js
_blocks.push(_dss.normalize(current_block.concat("\n #{{" + lineNum + "}}")));
```

The reason why I added this is so that I can easily get the css directly after the block so I don't have to duplicate scss that is already after the current block. Things like variables, functions, mixins, and placeholders.

**Comment by darcyclarke** [comment]
Better `block` and `line` management is coming soon, with `from` and `to` line numbers for both. 

> **For reference:** `block` implies the entire *comment block* a **variable** was found within whereas `line` referrers to the content associated with that variable.

**Comment by darcyclarke** [comment]
Should be in now: https://github.com/DSSWG/DSS/commit/9971cfd527ad3d3715e9d8ad4c9690d2dbbe5e2c
