### ISSUE TITLE
Enable multiple markup examples

### ISSUE THREAD

**Issue by arlodesign** [DSSWG/DSS#54]
I have button styles that can be applied to both ```<a>``` and ```<button>``` elements, so I'd like to include both markup examples:

```javascript
/**
  * @name Button
  * @description Your standard form button.
  * 
  * @state .is-primary - Indicates button is the primary action.
  * @state .is-smaller - A smaller button
  * 
  * @markup
  *   <button class="button">This is a button element</button>
  *
  * @markup
  *   <a href="#" class="button">This is an a element</button>
  */
```

However, this currently does not work. The line that is sent to the markup parser both times is still the first one. Here's the object I get from the above:

```javascript
{
    "blocks": [
        {
            "name": "Button",
            "description": "Your standard form button.",
            "state": [
                {
                    "name": ".is-primary",
                    "escaped": "is-primary",
                    "description": "Indicates button is the primary action."
                },
                {
                    "name": ".is-smaller",
                    "escaped": "is-smaller",
                    "description": "A smaller button"
                }
            ],
            "markup": [
                {
                    "example": "   <button class=\"button\">This is a button</button>\n  ",
                    "escaped": "   &lt;button class=\"button\"&gt;This is a button&lt;/button&gt;\n  "
                },
                {
                    "example": "   <button class=\"button\">This is a button</button>\n  ",
                    "escaped": "   &lt;button class=\"button\"&gt;This is a button&lt;/button&gt;\n  "
                }
            ]
        }
    ]
}
```

I've tried fixing it myself, but I'm having a hard time figuring out why the parser function in the parse method can return the correct line for multiple ```@state```s but not for multiple ```@markup```s. If this isn't on your roadmap, then I'm hoping you can explain a little about how that works so I can write my own parser method.

Please and thank you.

EDIT: I should elaborate and mention that I understand I could do:

```javascript
/**
  * @name Button
  * @description Your standard form button.
  * 
  * @state .is-primary - Indicates button is the primary action.
  * @state .is-smaller - A smaller button
  * 
  * @markup
  *   <button class="button">This is a button element</button>
  *   <a href="#" class="button">This is an a element</button>
  */
```

However, we're using the DSS as a separate library and not in conjunction with grunt-dss. We have a need to list those markup examples in separate chunks.

**Comment by operatino** [comment]
+1

**Comment by darcyclarke** [comment]
The `@markup` variable will be changing (in the works right now). I'll keep this in mind and try to implement it as well as the changes I noted in [this other comment](https://github.com/darcyclarke/DSS/issues/51#issuecomment-99222674).

**Comment by darcyclarke** [comment]
Should be fixed now: https://github.com/DSSWG/DSS/commit/9971cfd527ad3d3715e9d8ad4c9690d2dbbe5e2c
