### ISSUE TITLE
Multiline description support

### ISSUE THREAD

**Issue by operatino** [DSSWG/DSS#56]
Would be really helpful to be able adding more text in description

```
/**
  * @name Button
  * @description: 
           Your standard form button.
           With extended description.
  * 
  * @markup
  *   <button class="button">This is a button element</button>
  */ 
```

Having this feature, It will be also possible to add Markdown support, which is essential for semi-complex documentation pages.

**Comment by darcyclarke** [comment]
I'm considering a better way to be able to block out and parse variables which may fix this issue for you. The **colon (:)** is a good idea although I feel like it's unnecessary if I can figure out a way to chunk everything between one variable to the next together.

**Comment by darcyclarke** [comment]
Should be in now: https://github.com/DSSWG/DSS/commit/9971cfd527ad3d3715e9d8ad4c9690d2dbbe5e2c
